
The following have been reloaded with a version change:
  1) GCCcore/13.2.0 => GCCcore/10.3.0
  2) GMP/6.2.1-GCCcore-12.3.0 => GMP/6.2.1-GCCcore-10.3.0
  3) Python/3.11.5-GCCcore-13.2.0 => Python/3.9.5-GCCcore-10.3.0
  4) SQLite/3.43.1-GCCcore-13.2.0 => SQLite/3.35.4-GCCcore-10.3.0
  5) Tcl/8.6.13-GCCcore-13.2.0 => Tcl/8.6.11-GCCcore-10.3.0
  6) XZ/5.4.4-GCCcore-13.2.0 => XZ/5.2.5-GCCcore-10.3.0
  7) binutils/2.40-GCCcore-13.2.0 => binutils/2.36.1-GCCcore-10.3.0
  8) bzip2/1.0.8-GCCcore-13.2.0 => bzip2/1.0.8-GCCcore-10.3.0
  9) libffi/3.4.4-GCCcore-13.2.0 => libffi/3.3-GCCcore-10.3.0
 10) libreadline/8.2-GCCcore-13.2.0 => libreadline/8.1-GCCcore-10.3.0
 11) ncurses/6.4-GCCcore-13.2.0 => ncurses/6.2-GCCcore-10.3.0
 12) zlib/1.2.13-GCCcore-13.2.0 => zlib/1.2.11-GCCcore-10.3.0


The following have been reloaded with a version change:
  1) GCCcore/10.3.0 => GCCcore/11.3.0
  2) GMP/6.2.1-GCCcore-10.3.0 => GMP/6.2.1-GCCcore-11.3.0
  3) Python/3.9.5-GCCcore-10.3.0 => Python/3.10.4-GCCcore-11.3.0
  4) SQLite/3.35.4-GCCcore-10.3.0 => SQLite/3.38.3-GCCcore-11.3.0
  5) Tcl/8.6.11-GCCcore-10.3.0 => Tcl/8.6.12-GCCcore-11.3.0
  6) XZ/5.2.5-GCCcore-10.3.0 => XZ/5.2.5-GCCcore-11.3.0
  7) binutils/2.36.1-GCCcore-10.3.0 => binutils/2.38-GCCcore-11.3.0
  8) bzip2/1.0.8-GCCcore-10.3.0 => bzip2/1.0.8-GCCcore-11.3.0
  9) libffi/3.3-GCCcore-10.3.0 => libffi/3.4.2-GCCcore-11.3.0
 10) libreadline/8.1-GCCcore-10.3.0 => libreadline/8.1.2-GCCcore-11.3.0
 11) ncurses/6.2-GCCcore-10.3.0 => ncurses/6.3-GCCcore-11.3.0
 12) zlib/1.2.11-GCCcore-10.3.0 => zlib/1.2.12-GCCcore-11.3.0


The following have been reloaded with a version change:
  1) Brotli/1.1.0-GCCcore-13.2.0 => Brotli/1.0.9-GCCcore-12.3.0
  2) FFTW/3.3.10-GCC-13.2.0 => FFTW/3.3.10-GCC-12.3.0
  3) FlexiBLAS/3.3.1-GCC-13.2.0 => FlexiBLAS/3.3.1-GCC-12.3.0
  4) GCC/13.2.0 => GCC/12.3.0
  5) GCCcore/11.3.0 => GCCcore/12.3.0
  6) GMP/6.2.1-GCCcore-11.3.0 => GMP/6.2.1-GCCcore-12.3.0
  7) LibTIFF/4.6.0-GCCcore-13.2.0 => LibTIFF/4.5.0-GCCcore-12.3.0
  8) LittleCMS/2.15-GCCcore-13.2.0 => LittleCMS/2.15-GCCcore-12.3.0
  9) NASM/2.16.01-GCCcore-13.2.0 => NASM/2.16.01-GCCcore-12.3.0
 10) OpenBLAS/0.3.24-GCC-13.2.0 => OpenBLAS/0.3.23-GCC-12.3.0
 11) OpenJPEG/2.5.0-GCCcore-13.2.0 => OpenJPEG/2.5.0-GCCcore-12.3.0
 12) Pillow/10.2.0-GCCcore-13.2.0 => Pillow/10.0.0-GCCcore-12.3.0
 13) Python-bundle-PyPI/2023.10-GCCcore-13.2.0 => Python-bundle-PyPI/2023.06-GCCcore-12.3.0
 14) Python/3.10.4-GCCcore-11.3.0 => Python/3.11.3-GCCcore-12.3.0
 15) SQLite/3.38.3-GCCcore-11.3.0 => SQLite/3.42.0-GCCcore-12.3.0
 16) SciPy-bundle/2023.11-gfbf-2023b => SciPy-bundle/2023.07-gfbf-2023a
 17) Tcl/8.6.12-GCCcore-11.3.0 => Tcl/8.6.13-GCCcore-12.3.0
 18) X11/20231019-GCCcore-13.2.0 => X11/20230603-GCCcore-12.3.0
 19) XZ/5.2.5-GCCcore-11.3.0 => XZ/5.4.2-GCCcore-12.3.0
 20) binutils/2.38-GCCcore-11.3.0 => binutils/2.40-GCCcore-12.3.0
 21) bzip2/1.0.8-GCCcore-11.3.0 => bzip2/1.0.8-GCCcore-12.3.0
 22) cffi/1.15.1-GCCcore-13.2.0 => cffi/1.15.1-GCCcore-12.3.0
 23) cryptography/41.0.5-GCCcore-13.2.0 => cryptography/41.0.1-GCCcore-12.3.0
 24) expat/2.5.0-GCCcore-13.2.0 => expat/2.5.0-GCCcore-12.3.0
 25) fontconfig/2.14.2-GCCcore-13.2.0 => fontconfig/2.14.2-GCCcore-12.3.0
 26) freetype/2.13.2-GCCcore-13.2.0 => freetype/2.13.0-GCCcore-12.3.0
 27) gfbf/2023b => gfbf/2023a
 28) giflib/5.2.1-GCCcore-13.2.0 => giflib/5.2.1-GCCcore-12.3.0
 29) gzip/1.13-GCCcore-13.2.0 => gzip/1.12-GCCcore-12.3.0
 30) jbigkit/2.1-GCCcore-13.2.0 => jbigkit/2.1-GCCcore-12.3.0
 31) libdeflate/1.19-GCCcore-13.2.0 => libdeflate/1.18-GCCcore-12.3.0
 32) libffi/3.4.2-GCCcore-11.3.0 => libffi/3.4.4-GCCcore-12.3.0
 33) libjpeg-turbo/3.0.1-GCCcore-13.2.0 => libjpeg-turbo/2.1.5.1-GCCcore-12.3.0
 34) libpciaccess/0.17-GCCcore-13.2.0 => libpciaccess/0.17-GCCcore-12.3.0
 35) libpng/1.6.40-GCCcore-13.2.0 => libpng/1.6.39-GCCcore-12.3.0
 36) libreadline/8.1.2-GCCcore-11.3.0 => libreadline/8.2-GCCcore-12.3.0
 37) libwebp/1.3.2-GCCcore-13.2.0 => libwebp/1.3.1-GCCcore-12.3.0
 38) lz4/1.9.4-GCCcore-13.2.0 => lz4/1.9.4-GCCcore-12.3.0
 39) ncurses/6.3-GCCcore-11.3.0 => ncurses/6.4-GCCcore-12.3.0
 40) pybind11/2.11.1-GCCcore-13.2.0 => pybind11/2.11.1-GCCcore-12.3.0
 41) util-linux/2.39-GCCcore-13.2.0 => util-linux/2.39-GCCcore-12.3.0
 42) virtualenv/20.24.6-GCCcore-13.2.0 => virtualenv/20.23.1-GCCcore-12.3.0
 43) xorg-macros/1.20.0-GCCcore-13.2.0 => xorg-macros/1.20.0-GCCcore-12.3.0
 44) zlib/1.2.12-GCCcore-11.3.0 => zlib/1.2.13-GCCcore-12.3.0
 45) zstd/1.5.5-GCCcore-13.2.0 => zstd/1.5.5-GCCcore-12.3.0


The following have been reloaded with a version change:
  1) Brotli/1.0.9-GCCcore-12.3.0 => Brotli/1.1.0-GCCcore-13.2.0
  2) FFTW/3.3.10-GCC-12.3.0 => FFTW/3.3.10-GCC-13.2.0
  3) FlexiBLAS/3.3.1-GCC-12.3.0 => FlexiBLAS/3.3.1-GCC-13.2.0
  4) GCC/12.3.0 => GCC/13.2.0
  5) GCCcore/12.3.0 => GCCcore/13.2.0
  6) LibTIFF/4.5.0-GCCcore-12.3.0 => LibTIFF/4.6.0-GCCcore-13.2.0
  7) LittleCMS/2.15-GCCcore-12.3.0 => LittleCMS/2.15-GCCcore-13.2.0
  8) NASM/2.16.01-GCCcore-12.3.0 => NASM/2.16.01-GCCcore-13.2.0
  9) OpenBLAS/0.3.23-GCC-12.3.0 => OpenBLAS/0.3.24-GCC-13.2.0
 10) OpenJPEG/2.5.0-GCCcore-12.3.0 => OpenJPEG/2.5.0-GCCcore-13.2.0
 11) Pillow/10.0.0-GCCcore-12.3.0 => Pillow/10.2.0-GCCcore-13.2.0
 12) Python-bundle-PyPI/2023.06-GCCcore-12.3.0 => Python-bundle-PyPI/2023.10-GCCcore-13.2.0
 13) Python/3.11.3-GCCcore-12.3.0 => Python/3.11.5-GCCcore-13.2.0
 14) SQLite/3.42.0-GCCcore-12.3.0 => SQLite/3.43.1-GCCcore-13.2.0
 15) SciPy-bundle/2023.07-gfbf-2023a => SciPy-bundle/2023.11-gfbf-2023b
 16) Tcl/8.6.13-GCCcore-12.3.0 => Tcl/8.6.13-GCCcore-13.2.0
 17) X11/20230603-GCCcore-12.3.0 => X11/20231019-GCCcore-13.2.0
 18) XZ/5.4.2-GCCcore-12.3.0 => XZ/5.4.4-GCCcore-13.2.0
 19) binutils/2.40-GCCcore-12.3.0 => binutils/2.40-GCCcore-13.2.0
 20) bzip2/1.0.8-GCCcore-12.3.0 => bzip2/1.0.8-GCCcore-13.2.0
 21) cffi/1.15.1-GCCcore-12.3.0 => cffi/1.15.1-GCCcore-13.2.0
 22) cryptography/41.0.1-GCCcore-12.3.0 => cryptography/41.0.5-GCCcore-13.2.0
 23) expat/2.5.0-GCCcore-12.3.0 => expat/2.5.0-GCCcore-13.2.0
 24) fontconfig/2.14.2-GCCcore-12.3.0 => fontconfig/2.14.2-GCCcore-13.2.0
 25) freetype/2.13.0-GCCcore-12.3.0 => freetype/2.13.2-GCCcore-13.2.0
 26) gfbf/2023a => gfbf/2023b
 27) giflib/5.2.1-GCCcore-12.3.0 => giflib/5.2.1-GCCcore-13.2.0
 28) gzip/1.12-GCCcore-12.3.0 => gzip/1.13-GCCcore-13.2.0
 29) jbigkit/2.1-GCCcore-12.3.0 => jbigkit/2.1-GCCcore-13.2.0
 30) libdeflate/1.18-GCCcore-12.3.0 => libdeflate/1.19-GCCcore-13.2.0
 31) libffi/3.4.4-GCCcore-12.3.0 => libffi/3.4.4-GCCcore-13.2.0
 32) libjpeg-turbo/2.1.5.1-GCCcore-12.3.0 => libjpeg-turbo/3.0.1-GCCcore-13.2.0
 33) libpciaccess/0.17-GCCcore-12.3.0 => libpciaccess/0.17-GCCcore-13.2.0
 34) libpng/1.6.39-GCCcore-12.3.0 => libpng/1.6.40-GCCcore-13.2.0
 35) libreadline/8.2-GCCcore-12.3.0 => libreadline/8.2-GCCcore-13.2.0
 36) libwebp/1.3.1-GCCcore-12.3.0 => libwebp/1.3.2-GCCcore-13.2.0
 37) lz4/1.9.4-GCCcore-12.3.0 => lz4/1.9.4-GCCcore-13.2.0
 38) ncurses/6.4-GCCcore-12.3.0 => ncurses/6.4-GCCcore-13.2.0
 39) pybind11/2.11.1-GCCcore-12.3.0 => pybind11/2.11.1-GCCcore-13.2.0
 40) util-linux/2.39-GCCcore-12.3.0 => util-linux/2.39-GCCcore-13.2.0
 41) virtualenv/20.23.1-GCCcore-12.3.0 => virtualenv/20.24.6-GCCcore-13.2.0
 42) xorg-macros/1.20.0-GCCcore-12.3.0 => xorg-macros/1.20.0-GCCcore-13.2.0
 43) zlib/1.2.13-GCCcore-12.3.0 => zlib/1.2.13-GCCcore-13.2.0
 44) zstd/1.5.5-GCCcore-12.3.0 => zstd/1.5.5-GCCcore-13.2.0

Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
Traceback (most recent call last):
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/run.py", line 231, in <module>
    exp.train(setting)
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/exp/exp_long_term_forecasting.py", line 234, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 572, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/fs47816/workdir/sample_scripts/time_series_dl/time-series-v5/Time-Series-Library/models/PatchTST_sepcmix_simple.py", line 417, in forecast
    enc_out_sh_pre, attns_sh_pre = self.encoder_sh_pre(enc_out_sh_pre)
                                   ^^^^^^^^^^^^^^^^^^^
  File "/apps/eb/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'encoder_sh_pre'. Did you mean: 'encoder_sh'?
slurmstepd: error: *** JOB 36974792 ON b8-2 CANCELLED AT 2025-05-12T08:26:07 DUE TO TIME LIMIT ***
